### ISSUE TITLE
TAB not sent to emulator.

### ISSUE THREAD

**Issue by ks-ascendum** [sh95014/AppleWin#31]
TAB not being sent to emulator.

In Nox Archaist, TAB is used to open the inventory. Does not work under this emulator.

**Comment by sh95014** [comment]
Just checked, the code does seem to receive the tab key (`kVK_Tab`) from the system and send it on to the emulator.

I tried Bank Street Writer, and 'tab' does seem to work. You can check by invoking the menu with `ESC` and tabbing around the various options. It also works in DOS (press 'tab' and then 'return', and you should get a `?SYNTAX ERROR` instead of nothing as if you just pressed `return`).

Are you using the pre-built binary or compiling your own? If the latter, can you help me set a breakpoint if it hits? I want to know if this case in `EmulatorView.m` hits when you press 'tab':

```
        case kVK_Tab:
            ch = ASCII_HT;
            break;
```

then whether it gets inside:

```
    if (ch >= ASCII_NUL) {
        addKeyToBuffer(ch);
    }
```

and what the value of `ch` is at that point.

Relating to https://github.com/sh95014/AppleWin/issues/9

**Comment by beheybird** [comment]
I tried this out. The release version doesn't see tab. I compiled the latest version and tab works. Nox Archaist functions correctly.

**Comment by sh95014** [comment]
Weird! Let me make a new release build when I get a minute and see if that resolves the issue then. Thanks!

**Comment by sh95014** [comment]
D'oh, this was fixed with https://github.com/audetto/AppleWin/commit/d073c3b669c810504055ae273a26b34a3a36e264 after I made the 1.0 build.

I made a new binary [release 1.1 (1)](https://github.com/sh95014/AppleWin/releases/tag/Mariani-1.1-1) that should resolve this issue, please let me know if you continue to run into problems.

**Comment by sh95014** [comment]
Please let me know if you still encounter this issue.
